modLoader="javafml"
loaderVersion="[1,)"
license="ARR"
[[mods]]
modId="mixy"
version="${version}"
displayName="Mixy"
displayTest = "IGNORE_SERVER_VERSION"
#logoFile="assets/voxy/icon.png"
authors="Cortex, Ferri_Arnus"
description='''
Far distance rendering mod utilising LoDs
'''

[[dependencies.mixy]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mixy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mixy]]
modId = "embeddium"
mandatory = true
versionRange = "[0.2.2+mc1.20.1, )"
ordering = "NONE"
side = "CLIENT"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[mods]]
modId="voxy"
displayName="Voxy (Mixy)"
version="${version}"
authors="Cortex"
license="ARR"
logoFile="assets/voxy/icon.png"
description='''
Far distance rendering mod utilising LoDs
'''